#!/usr/bin/env node
/**
 * seed-iaps.mjs
 *
 * Seeds the InstrumentApproach model in DynamoDB via the Amplify Data API.
 * Reads iaps.json (generated by parse-dtpp.mjs) and creates records in batches.
 *
 * Prerequisites:
 *   1. npm run parse-nasr         — generate src/data/airports.full.json
 *   2. npm run parse-dtpp         — generate src/data/iaps.json
 *   3. npm run seed-airports      — airports must be in DynamoDB first
 *   4. npx ampx sandbox           — local sandbox must be running (or deployed)
 *   5. amplify_outputs.json       — must exist (generated by sandbox/deploy)
 *
 * Usage:
 *   node scripts/seed-iaps.mjs
 *   npm run seed-iaps
 *
 * Joining strategy:
 *   iaps.json has faaAptIdent + icaoIdent.
 *   airports.full.json has nasrSiteNo + faaId + icaoId.
 *   We build an in-memory lookup map and join before seeding.
 *   IAPs with no matching airport are skipped and logged.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const IAPS_FILE = args[0] ?? path.join(__dirname, "data", "iaps.json");
const AIRPORTS_FILE =
  args[1] ?? path.join(__dirname, "data", "airports.full.json");
const OUTPUTS = args[2] ?? path.join(__dirname, "..", "amplify_outputs.json");

// ── Validate inputs ───────────────────────────────────────────────────────────

if (!fs.existsSync(IAPS_FILE)) {
  console.error(`\n❌  iaps.json not found. Run: npm run parse-dtpp\n`);
  process.exit(1);
}

if (!fs.existsSync(AIRPORTS_FILE)) {
  console.error(
    `\n❌  airports.full.json not found. Run: npm run parse-nasr\n`,
  );
  process.exit(1);
}

if (!fs.existsSync(OUTPUTS)) {
  console.error(`\n❌  amplify_outputs.json not found.`);
  console.error(`    Run: npx ampx sandbox   (and wait for it to finish)\n`);
  process.exit(1);
}

const outputs = JSON.parse(fs.readFileSync(OUTPUTS, "utf8"));
const iaps = JSON.parse(fs.readFileSync(IAPS_FILE, "utf8"));
const airports = JSON.parse(fs.readFileSync(AIRPORTS_FILE, "utf8"));

// ── Validate outputs ──────────────────────────────────────────────────────────

const apiUrl = outputs?.data?.url;
const apiKey = outputs?.data?.api_key;

if (!apiUrl) {
  console.error(`\n❌  No data.url found in amplify_outputs.json\n`);
  process.exit(1);
}

if (!apiKey) {
  console.error(`\n❌  No data.api_key found in amplify_outputs.json`);
  console.error(
    `    The InstrumentApproach model needs API key auth for seeding.\n`,
  );
  process.exit(1);
}

// ── Build airport lookup map ──────────────────────────────────────────────────
// Primary key: FAA ID (always present)
// Secondary key: ICAO ID (present for most IFR airports)
// Some d-TPP entries use ICAO as the apt_ident (e.g. Alaskan airports),
// so we index both directions.

const byFaaId = new Map(); // faaId  → { nasrSiteNo, icaoId }
const byIcaoId = new Map(); // icaoId → { nasrSiteNo, faaId }

for (const apt of airports) {
  if (apt.faaId) byFaaId.set(apt.faaId.toUpperCase(), apt);
  if (apt.icaoId) byIcaoId.set(apt.icaoId.toUpperCase(), apt);
}

function resolveAirport(iap) {
  // Try FAA ID first
  if (iap.faaAptIdent) {
    const match = byFaaId.get(iap.faaAptIdent.toUpperCase());
    if (match) return match;
  }
  // Fall back to ICAO ID
  if (iap.icaoIdent) {
    const match = byIcaoId.get(iap.icaoIdent.toUpperCase());
    if (match) return match;
  }
  return null;
}

// ── Join & prepare records ────────────────────────────────────────────────────

const records = [];
const unmatched = [];

for (const iap of iaps) {
  const apt = resolveAirport(iap);

  if (!apt) {
    unmatched.push(iap.faaAptIdent || iap.icaoIdent);
    continue;
  }

  // Build the DynamoDB input — strip nulls
  const record = {
    nasrSiteNo: apt.nasrSiteNo,
    airportId: apt.icaoId || apt.faaId,
    procedureName: iap.procedureName,
    runway: iap.runway,
    suffix: iap.suffix ?? undefined,
    navType: iap.navType,
    isPrecision: iap.isPrecision,
    isCircling: iap.isCircling,

    // Minima — null for now, populated later from CIFP or manual data
    straightInDaMsl: iap.straightInDaMsl ?? undefined,
    straightInVisSm: iap.straightInVisSm ?? undefined,
    straightInRvrFt: iap.straightInRvrFt ?? undefined,
    circlingMdaMsl: iap.circlingMdaMsl ?? undefined,
    circlingVisSm: iap.circlingVisSm ?? undefined,

    // Equipment
    approachLighting: iap.approachLighting ?? undefined,
    hasTdzl: iap.hasTdzl ?? undefined,
    hasCl: iap.hasCl ?? undefined,
    hasGlideslope: iap.hasGlideslope ?? undefined,
    hasLocalizer: iap.hasLocalizer ?? undefined,
    dmeRequired: iap.dmeRequired ?? undefined,
    radarRequired: iap.radarRequired ?? undefined,

    // Chart metadata
    pdfName: iap.pdfName ?? undefined,
    chartCycle: iap.chartCycle ?? undefined,
    amdtnum: iap.amdtnum ?? undefined,
    amdtdate: iap.amdtdate ?? undefined,

    // Airport identifiers (denormalized from d-TPP)
    faaAptIdent: iap.faaAptIdent ?? undefined,
    icaoIdent: iap.icaoIdent ?? undefined,

    nasrCycleDate: iap.nasrCycleDate,
  };

  // Strip undefined values
  const clean = Object.fromEntries(
    Object.entries(record).filter(([, v]) => v !== undefined && v !== null),
  );

  records.push(clean);
}

console.log(`\n🌐  API endpoint: ${apiUrl}`);
console.log(`📦  IAP records to seed: ${records.length.toLocaleString()}`);
if (unmatched.length > 0) {
  // Deduplicate for display
  const uniqueUnmatched = [...new Set(unmatched)];
  console.log(
    `⚠️   Unmatched airports (no NASR record): ${uniqueUnmatched.length}`,
  );
  if (uniqueUnmatched.length <= 20) {
    console.log(`    ${uniqueUnmatched.join(", ")}`);
  } else {
    console.log(`    First 20: ${uniqueUnmatched.slice(0, 20).join(", ")} ...`);
  }
}
console.log();

// ── GraphQL mutation ──────────────────────────────────────────────────────────

const CREATE_IAP = /* GraphQL */ `
  mutation CreateInstrumentApproach($input: CreateInstrumentApproachInput!) {
    createInstrumentApproach(input: $input) {
      id
      airportId
      procedureName
    }
  }
`;

async function gql(query, variables) {
  const res = await fetch(apiUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
    },
    body: JSON.stringify({ query, variables }),
  });
  return res.json();
}

// ── Seed in batches ───────────────────────────────────────────────────────────

const BATCH = 25;
const DELAY_MS = 100;

let created = 0;
let failed = 0;
const errors = [];

const start = Date.now();

for (let i = 0; i < records.length; i += BATCH) {
  const batch = records.slice(i, i + BATCH);

  await Promise.all(
    batch.map(async (input) => {
      const result = await gql(CREATE_IAP, { input });

      if (result.errors) {
        const isDupe = result.errors.some(
          (e) =>
            e.message?.includes("ConditionalCheckFailedException") ||
            e.message?.includes("already exists"),
        );
        if (!isDupe) {
          failed++;
          errors.push({ input, errors: result.errors });
        }
      } else {
        created++;
      }
    }),
  );

  const pct = Math.round(((i + batch.length) / records.length) * 100);
  process.stdout.write(
    `\r  Progress: ${pct}%  (${created} created, ${failed} failed)`,
  );

  if (i + BATCH < records.length) {
    await new Promise((r) => setTimeout(r, DELAY_MS));
  }
}

const elapsed = ((Date.now() - start) / 1000).toFixed(1);

console.log(`\n\n✅  Seeding complete in ${elapsed}s`);
console.log(`    Created:   ${created}`);
console.log(`    Failed:    ${failed}`);
console.log(`    Unmatched: ${unmatched.length} (skipped — no airport record)`);

if (errors.length > 0) {
  console.log(`\n⚠️   First 5 errors (with full input):`);
  errors.slice(0, 5).forEach((e) => {
    console.log(`\n  Procedure: "${e.input.procedureName}"`);
    console.log(`  Input:`, JSON.stringify(e.input, null, 4));
    console.log(`  Error:`, e.errors[0]?.message);
  });
}

console.log();
