#!/usr/bin/env node
/**
 * seed-cifp.mjs
 *
 * Seeds the ApproachProcedure model in DynamoDB via the Amplify Data API.
 * Reads cifp-fixes.json (generated by parse-cifp.mjs) and upserts records.
 *
 * By default seeds only procedures for airports already in your Airport table
 * (i.e. airports you've flown to/from). Pass --all to seed everything (~65k procedures).
 *
 * Prerequisites:
 *   1. npm run parse-cifp              — generate scripts/data/cifp-fixes.json
 *   2. npx ampx sandbox (or deployed)  — schema must include approachProcedure model
 *   3. amplify_outputs.json            — must exist
 *
 * Usage:
 *   node scripts/seed-cifp.mjs                     # only airports in your Airport table
 *   node scripts/seed-cifp.mjs --all               # all ~65k procedures (slow)
 *   npm run seed-cifp
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/data";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const SEED_ALL   = args.includes("--all");
const DATA_FILE  = args.find((a) => a.endsWith(".json") && !a.includes("outputs")) ??
                   path.join(__dirname, "data", "cifp-fixes.json");
const OUTPUTS    = args.find((a) => a.includes("outputs")) ??
                   path.join(__dirname, "..", "amplify_outputs.json");

// ── Setup ─────────────────────────────────────────────────────────────────────

if (!fs.existsSync(DATA_FILE)) {
  console.error(`cifp-fixes.json not found: ${DATA_FILE}`);
  console.error("Run: npm run parse-cifp");
  process.exit(1);
}
if (!fs.existsSync(OUTPUTS)) {
  console.error(`amplify_outputs.json not found: ${OUTPUTS}`);
  process.exit(1);
}

const amplifyOutputs = JSON.parse(fs.readFileSync(OUTPUTS, "utf8"));
Amplify.configure(amplifyOutputs);
const client = generateClient();

// ── Load data ─────────────────────────────────────────────────────────────────

console.log(`Loading ${DATA_FILE}...`);
const procedures = JSON.parse(fs.readFileSync(DATA_FILE, "utf8"));
console.log(`Loaded ${procedures.length.toLocaleString()} procedures`);

// ── Filter to seeded airports (unless --all) ──────────────────────────────────

let toSeed = procedures;

if (!SEED_ALL) {
  console.log("Fetching airports already in your Airport table...");
  const seededIcaos = new Set();
  let token;
  try {
    do {
      const { data, nextToken, errors } = await client.models.airport.list({
        authMode:  "apiKey",
        limit:     1000,
        nextToken: token,
      });
      if (errors?.length) console.warn("Airport list errors:", errors);
      if (data?.length) console.log(`  fetched ${data.length} airports, sample:`, data[0]?.icaoId, data[0]?.faaId);
      for (const a of (data ?? [])) {
        if (a.icaoId) seededIcaos.add(a.icaoId);
        if (a.faaId)  seededIcaos.add(a.faaId);
      }
      token = nextToken;
    } while (token);
  } catch (err) {
    console.error("Failed to fetch airports:", err?.message ?? err);
    process.exit(1);
  }

  console.log(`Found ${seededIcaos.size} airports in table${seededIcaos.size ? ": " + [...seededIcaos].join(", ") : " (empty — check API key auth and schema deployment)"}`);
  if (seededIcaos.size === 0) {
    console.error("Airport table appears empty. Run: npm run seed-airports");
    console.error("Or run with --all to skip airport filtering: node scripts/seed-cifp.mjs --all");
    process.exit(1);
  }
  toSeed = procedures.filter((p) => seededIcaos.has(p.icao));
  console.log(`Filtered to ${toSeed.length.toLocaleString()} procedures for those airports`);
}

if (toSeed.length === 0) {
  console.log("Nothing to seed. Ensure airports are seeded first (npm run seed-airports).");
  process.exit(0);
}

// ── Seed ──────────────────────────────────────────────────────────────────────

const BATCH     = 20;   // concurrent mutations
const DELAY_MS  = 100;  // ms between batches

let seeded  = 0;
let skipped = 0;
let errors  = 0;

const createMutation = /* GraphQL */ `
  mutation CreateApproachProcedure($input: CreateApproachProcedureInput!) {
    createApproachProcedure(input: $input) { id }
  }
`;

async function seedOne(proc) {
  const input = {
    icao:       proc.icao,
    procedure:  proc.procedure,
    transition: proc.transition ?? null,
    routeType:  proc.routeType ?? null,
    cycleDate:  proc.cycleDate ?? null,
    fixes:      JSON.stringify(proc.fixes),
  };

  try {
    await client.graphql({
      query:     createMutation,
      variables: { input },
      authMode:  "apiKey",
    });
    seeded++;
  } catch (err) {
    const msg = err?.errors?.[0]?.message ?? String(err);
    if (msg.includes("ConditionalCheckFailed") || msg.includes("already exists")) {
      skipped++;
    } else {
      errors++;
      if (errors <= 5) console.error(`  Error seeding ${proc.icao}/${proc.procedure}: ${msg}`);
    }
  }
}

console.log(`\nSeeding ${toSeed.length.toLocaleString()} procedures (batch=${BATCH})...`);
const start = Date.now();

for (let i = 0; i < toSeed.length; i += BATCH) {
  const batch = toSeed.slice(i, i + BATCH);
  await Promise.all(batch.map(seedOne));
  if ((i + BATCH) % 200 === 0 || i + BATCH >= toSeed.length) {
    const pct = Math.min(100, Math.round(((i + BATCH) / toSeed.length) * 100));
    console.log(`  ${pct}% — seeded ${seeded}, skipped ${skipped}, errors ${errors}`);
  }
  if (i + BATCH < toSeed.length) await new Promise((r) => setTimeout(r, DELAY_MS));
}

const elapsed = ((Date.now() - start) / 1000).toFixed(1);
console.log(`\nDone in ${elapsed}s`);
console.log(`  Seeded:  ${seeded}`);
console.log(`  Skipped: ${skipped} (already existed)`);
console.log(`  Errors:  ${errors}`);
